using System;

namespace ObjectModel
{
	public enum HintMessageParameterType : byte
	{
		MessageId = 1,
		IsCompact = 83,
		MissionId = 2,
		MissionName,
		TaskId,
		TaskName,
		EventType,
		EventName,
		Level,
		Code,
		OrderIndex = 59,
		Title = 10,
		OriginalTitle = 73,
		Description = 12,
		OriginalDescription = 74,
		Tooltip = 69,
		OriginalTooltip = 75,
		Image = 13,
		ImageId = 46,
		ItemClass = 56,
		ItemId = 14,
		ItemName,
		ItemType = 57,
		ItemSubType,
		Storage = 68,
		SourceStorage = 82,
		InstanceId = 72,
		RodId = 63,
		Slot,
		CategoryId = 76,
		CategoryName,
		RootCategoryId = 85,
		RootCategoryName,
		MinLoad = 78,
		MaxLoad,
		MinThickness,
		MaxThickness,
		ElementId = 16,
		ScreenPosition,
		ScenePosition,
		ScenePositionOffset,
		Rotation,
		Scale,
		Geometry = 35,
		Spatial = 66,
		MarkerState,
		InteractiveObject = 36,
		InteractiveObjectId,
		AllowInteraction = 11,
		ActiveState = 45,
		InteractiveVersion = 52,
		ExecutionNextTime = 87,
		IsDisabled,
		StartTime,
		TimeToComplete,
		FishBox = 53,
		HitchBox,
		DynamicFish = 91,
		ShaderName = 22,
		ArrowType,
		ArrowType3D = 55,
		Side = 65,
		HighlightType = 24,
		KeyType = 38,
		GizmoType = 25,
		DashType = 62,
		ScreenType = 26,
		ScreenTab = 44,
		DisplayStorage = 70,
		IsAutoDestroy = 27,
		ShowAfterMs,
		ShowDuringMs,
		IsAutomatic = 71,
		Color = 30,
		HintType,
		BackgroundColor = 39,
		BackgroundType,
		Alignment,
		Padding,
		CommandType = 32,
		CommandName = 43,
		CommandArgument = 33,
		Count,
		Value = 47,
		Length,
		Weight,
		Temparature,
		Speed,
		Min = 60,
		Max
	}
}
