using System;

namespace ObjectModel
{
	public enum ItemSubTypes : short
	{
		All,
		Outfit,
		Rod,
		Reel,
		TerminalTackle,
		Line,
		Hook,
		Bobber,
		Sinker,
		SpinningSinker = 144,
		DropSinker = 147,
		Feeder = 9,
		Bait,
		Lure,
		JigBait,
		Tool,
		Property = 15,
		Misc,
		Boat = 60,
		RodCase = 17,
		LuresBox,
		Waistcoat = 21,
		Boots = 19,
		Hat = 22,
		Clothing = 86,
		Belt,
		RescueVest = 20,
		Glasses = 62,
		Gloves = 88,
		Talisman,
		TelescopicRod = 23,
		MatchRod,
		SpinningRod,
		CastingRod,
		FeederRod,
		BottomRod,
		FlyRod,
		CarpRod = 129,
		SpodRod,
		SpinReel = 30,
		LineRunningReel,
		CastReel,
		FlyReel,
		JigHead = 35,
		MonoLine,
		BraidLine,
		FlurLine,
		SimpleHook,
		LongHook,
		BarblessHook,
		CarpHook = 131,
		OffsetHook = 145,
		Waggler = 151,
		Slider,
		CommonBait = 42,
		BoilBait,
		BoilBait_Boils = -431,
		BoilBait_Pellets = -432,
		InsectsWormBait = 44,
		FreshBait = 34,
		Spoon = 45,
		Spinner,
		Spinnerbait,
		Cranckbait,
		Popper,
		Swimbait,
		Jerkbait,
		BassJig,
		BarblessSpoons = 94,
		BarblessSpinners,
		Frog = 58,
		Walker = 97,
		Minnow = 139,
		BuzzBait = 149,
		CommonJigHeads = 93,
		BarblessJigHeads = 92,
		Worm = 53,
		Grub,
		Shad,
		Tube,
		Craw,
		Tail = 146,
		Slug = 150,
		SounderBattery = 72,
		Keepnet = 75,
		Stringer = 96,
		FishNet = 76,
		TrollingRodStand,
		RodStand,
		EchoSounder,
		Tent,
		Chair,
		Umbrella,
		Cooker,
		Radio,
		Car = 59,
		Lodge = 61,
		Kayak = 98,
		RubberDinghy,
		Zodiak,
		FlatBottomedBoat,
		MotorBoat,
		BassBoat,
		Airboat,
		DeckBoat,
		FishingYacht,
		BoatGear = 110,
		BoatMotor = 107,
		BoatFuel,
		BoatOar,
		BoatFishBox = 111,
		BoatLight,
		BoatAnchor,
		Repellent = 73,
		Food,
		Attractant = 90,
		Firework,
		Bell = 63,
		CommonBell,
		ElectronicBell,
		RepairKit = 69,
		RodRepairKit,
		ReelRepairKit,
		MissionItem = 115,
		UnderwaterItem,
		Weed = 114,
		ShoreWeed = 117,
		Sticks,
		Cork,
		Shell,
		Creature,
		Loot,
		Trash,
		Leader = 66,
		MonoLeader,
		FlurLeader,
		BraidLeader = 124,
		SteelLeader,
		TitaniumLeader = 148,
		CarpLeader = 132,
		CarolinaRig = 140,
		TexasRig = 142,
		ThreewayRig,
		CageFeeder = 133,
		FlatFeeder,
		PvaFeeder,
		SpodFeeder,
		Chum = 85,
		ChumBase = 126,
		ChumParticle,
		ChumAroma,
		ChumGroundbaits = 137,
		ChumCarpbaits,
		ChumMethodMix = 141,
		ChumCarpbaits_ChumBoils = -1381,
		ChumCarpbaits_ChumPellets = -1382,
		ChumCarpbaits_ChumSpodMix = -1383
	}
}
