using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BiteEditor
{
	[JsonConverter(typeof(StringEnumConverter))]
	public enum FishName
	{
		None,
		Pumpkinseed = 61,
		Bluegill,
		Warmouth,
		RedearSunfish,
		RedbreastSunfish,
		GreenSunfish,
		SpottedSunfish,
		BluespottedSunfish,
		Oscar,
		LeprechaunFish,
		WhiteCrappie,
		BlackCrappie,
		GoldenShiner,
		BluntnoseMinnow,
		CommonShiner,
		BlacktailShiner,
		CaliforniaRoach,
		LakeChub,
		FreshwaterDrum,
		YellowPerch = 81,
		Walleye = 83,
		ShinerPerch,
		EuropeanPerch,
		Sauger,
		Zander,
		VolgaZander,
		EurasianRuffe,
		CommonCarp,
		WhiteSucker,
		SmallmouthBuffalo,
		LongnoseSucker,
		MirrorCarp,
		NakedCarp,
		GhostCarp,
		CommonTench,
		CommonBream,
		SilverPrussianCarp,
		RedfinPickerel = 101,
		GrassPickerel,
		ChainPickerel,
		NorthernPike,
		Muskie,
		TigerMuskie,
		ClearMuskie,
		LargemouthBass = 111,
		SmallmouthBass,
		StripedBass,
		SpottedBass,
		RockBass,
		ButterflyPeacockBass,
		WhiteBass,
		SpeckledPeacockBass,
		NorthernSmallmouthBassBass,
		ChannelCatfish,
		BlueCatfish,
		FlatheadCatfish,
		BrownBullheadCatfish,
		BlackBullheadCatfish,
		WhiteCatfish,
		WelsCatfish,
		RainbowTrout = 501,
		SteelheadTrout,
		CutthroatTrout,
		BrookTrout,
		BrownTrout,
		LakeTrout,
		FremontRiverRainbowTrout,
		ColoradoGoldenTrout,
		DollyVarden,
		ArcticGrayling,
		Salwelinus,
		Splake,
		OregonRedbandTrout,
		TigerTrout,
		EuropeanGrayling,
		MarbleTrout,
		CreekBrownTrout,
		Lenok,
		EuropeanBrownTrout,
		FurryTrout = 590,
		WhiteSturgeon = 600,
		Sterlet,
		Beluga,
		LakeSturgeon,
		ChinookSalmon = 701,
		AtlanticSalmon,
		SockeyeSalmon,
		PinkSalmon,
		CohoSalmon,
		ChumSalmon,
		LakeWhitefish,
		CommonWhitefish,
		SiberianTaimen,
		Vendace = 711,
		AlligatorGar = 801,
		FloridaGar,
		LongnoseGar,
		BlackGar,
		MonsterGar,
		AlbinoGar,
		SpottedGar = 808,
		Tarpon = 900,
		Bowfin,
		Burbot,
		AmericanShad,
		AlaskaBlackfish,
		Paddlefish,
		RedDrum,
		CommonSnook,
		GafftopsailCatfish,
		EuropeanChub,
		GoldenTench,
		CommonRoach,
		Asp,
		CrucianCarp,
		CommonRudd,
		SilverBream,
		BlueBream,
		Gudgeon,
		Ide,
		CaspianRoach,
		GrassCarp,
		CommonBleak,
		WhiteeyeBream,
		EuropeanBitterling,
		CommonDace,
		Ziege,
		CommonBarbel,
		CommonNase,
		MonkeyGoby,
		RoundGoby,
		EuropeanEel,
		EuropeanWeatherfish,
		ChineseSleeper,
		ThicklipGreyMullet,
		EuropeanFlounder,
		BigheadCarp,
		SilverCarp,
		HybridF1Carp,
		Permit,
		Bonefish,
		SouthernFlounder,
		BlackDrum = 1530,
		GizzardShad = 1540,
		BigmouthBuffalo = 1580,
		ShoalBass = 1590,
		RedtailCatfish = 1300,
		GildedCatfish = 1310,
		Piraiba = 1320,
		SorubimCatfish = 1330,
		FlatwhiskeredCatfish = 1340,
		Jacunda = 1350,
		BandedAracu = 1370,
		SpottedAracu = 1400,
		RedTailBarracuda = 1420,
		RipsawCatfish = 1440,
		RedBelliedPiranha = 1480,
		RedeyePiranha = 1500,
		Tambaqui = 1520,
		Payara = 1650,
		Biara = 1660,
		SilverArowana = 1680,
		Arapaima = 1690,
		Brycon = 1710,
		FlagTailedProchilodus = 1720,
		SilverCroaker = 1730,
		HistoricSpottedBass = 1000,
		HistoricWhiteCrappie,
		HistoricChainPickerel,
		HistoricCutthroatTrout,
		HistoricSmallmouthBass,
		HistoricRainbowTrout,
		HistoricLargemouthBass,
		HistoricChinookSalmon,
		HistoricMuskie,
		RowdyBass,
		HistoricButterflyPeacockBass,
		HistoricStripedBass,
		GhostPike,
		BluegillSkeleton,
		AntleredSalmon,
		MonsterMuskie,
		MonsterFlathead,
		MonsterBowfin,
		MonsterWalleye,
		MonsterCutthroatTrout,
		MonsterLongnoseGar,
		MonsterTarpon,
		MonsterBurbot,
		MonsterStripedBass,
		MonsterAlaskaBlackfish,
		MonsterSmallmouthBuffalo
	}
}
